### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getUri' of undefined

### ISSUE THREAD

**Issue by navio** [yosuke-furukawa/language-jsx#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [language-jsx](https://github.com/yosuke-furukawa/language-jsx) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getUri' of undefined

```
At /Users/alnavarro/.atom/packages/language-jsx/lib/jsx.coffee:21

TypeError: Cannot read property 'getUri' of undefined
  at Object.module.exports.run (/Users/alnavarro/.atom/packages/language-jsx/lib/jsx.coffee:21:17)
  at atom-workspace.<anonymous> (/Users/alnavarro/.atom/packages/language-jsx/lib/jsx.coffee:7:47)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
  2x -0:50.8 core:backspace (atom-text-editor.editor)
  2x -0:45.2 core:move-right (atom-text-editor.editor)
  2x -0:43.9 core:move-down (atom-text-editor.editor)
     -0:42.9 run:file (atom-text-editor.editor)
     -0:41.5 jsx:run (div.atom-runner)
  4x -0:20.1 core:move-left (atom-text-editor.editor)
     -0:18.7 core:backspace (atom-text-editor.editor)
  3x -0:17.0 core:select-right (atom-text-editor.editor)
  3x -0:15.2 core:move-down (atom-text-editor.editor)
  2x -0:14.2 core:move-left (atom-text-editor.editor)
  2x -0:10.2 core:move-right (atom-text-editor.editor)
     -0:06.8 core:backspace (atom-text-editor.editor)
     -0:04.7 core:move-right (atom-text-editor.editor)
  2x -0:04.3 core:backspace (atom-text-editor.editor)
     -0:01.8 run:file (atom-text-editor.editor)
     -0:00.8 jsx:run (div.atom-runner)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.2.0
jshint, v1.2.0
language-jsx, v0.1.4
seti-syntax, v0.2.1
seti-ui, v0.6.1

# Dev
No dev packages
```

**Comment by yosuke-furukawa** [comment]
I have not published this library. thanks.
