### ISSUE TITLE
Failed to activate the language-jsx package

### ISSUE THREAD

**Issue by damkraw** [yosuke-furukawa/language-jsx#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [language-jsx](https://github.com/yosuke-furukawa/language-jsx) package, v0.1.4

### Stack Trace

Failed to activate the language-jsx package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/damian/.atom/packages/language-jsx/lib/jsx.coffee:10:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-yaml",
      "minimap",
      "wrap-guide",
      "metrics",
      "language-toml",
      "language-mustache",
      "language-make",
      "open-on-github",
      "package-generator"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
color-picker, v1.7.0
js-refactor, v0.3.0
language-jsx, v0.1.4
layout-manager, v0.2.3
linter, v0.12.1
linter-csslint, v0.0.11
linter-htmlhint, v0.0.13
linter-jshint, v0.1.2
node-resolver, v1.0.1
npm-docs, v0.2.0
react, v0.11.6
refactor, v0.4.1

# Dev
No dev packages
```

**Comment by yosuke-furukawa** [comment]
I have not published this library. thanks.
